---

    - name: update
      apt: update_cache=yes

    - name: install nginx
      apt: name=nginx state=latest

    - name: start nginx
      service: name=nginx state=started

    - name: copy index file for nginx from template
      template:
        src: "{{ proj_dir }}/roles/nginx/templates/indexfile.j2" 
        dest: "{{ nginx_web }}/index.html"

    - name: update owner for index file
      file:
        path: "{{ nginx_web }}/index.html" 
        owner: root 
        group: root
